import { Fira_Code } from 'next/font/google';
import "./globals.css";

const fira = Fira_Code({
  subsets: ["latin"],
});

export const metadata = {
  title: "Yeyati Prasher",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fira.className} antialiased`}
      >
        {/* Background Image */}
        <div className="fixed inset-0 z-0">
          <img
            src="/blurback.png"
            alt="Background"
            className="w-full h-full object-cover object-center"
          />
        </div>
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
